before_script:
  - docker login --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD

stages:
  - build
  - deploy

variables:
  TAG: $CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID-$CI_COMMIT_SHORT_SHA

install:
  stage: install
  image: node:18
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

build:dev:
  stage: build
  image: node:18
  script:
    - npm ci
    - npm run build
    - docker build -t frontend .
    - docker push frontend
  artifacts:
    paths:
      - build/
  tags:
    - dev
  only:
    - dev
  environment: dev

deploy:
  stage: deploy
  image: docker:latest
  script:
    - echo "Запуск скрипта развертывания..."
    - docker stack deploy -c dev.yml --with-registry-auth frontend_stack
  tags:
    - dev
  only:
    - dev
  environment: dev