before_script:
  - docker login --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD

stages:
  - build
  - deploy

variables:
  TAG: $CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID-$CI_COMMIT_SHORT_SHA

build:dev:
  stage: build
  image: node:18
  script:
    - docker build -t $CI_REGISTRY_IMAGE:frontend-$TAG .
    - docker push $CI_REGISTRY_IMAGE:frontend-$TAG
  tags:
    - dev
  only:
    - dev
  environment: dev

deploy:
  stage: deploy
  script:
    - echo "Запуск скрипта развертывания..."
    - docker stack deploy -c dev.yml --with-registry-auth frontend_stack
  tags:
    - dev
  only:
    - dev
  environment: dev