version: "3.9"
services:
  frontend:
    image: front-$IMAGE_NAME-$TAG
    command: ["npm", "run", "build"]
    tty: true
    build: .
    env_file:
      - .env.development
    ports:
      - "3000:80"
    restart: always